name: MongoDB K8s Monitoring

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push Image
      run: |
        echo "${{secrets.DOCKERPW}}" | docker login -u "harishnaga07" --password-stdin
        docker image build -t harishnaga07/image:latest-v1 .
        docker push harishnaga07/image:latest-v1
